version: "3"
services:
  app:
    build: ./app
    command: gunicorn --bind 0.0.0.0:8000 server:app --reload
    volumes:
      - ./app/src/:/usr/src/app/

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/files:/etc/nginx/certs
    depends_on:
      - app